const mainFunctions = require("./main");

module.exports = {
  // main Database
  // User Db Object
  dbCreateUser: mainFunctions.dbCreateUser,
  dbUpdateUser: mainFunctions.dbUpdateUser,
  dbDeleteUser: mainFunctions.dbDeleteUser,
  dbUpdateUserrole: mainFunctions.dbUpdateUserrole,
  dbUpdatePassword: mainFunctions.dbUpdatePassword,
  dbRegisterTenantuser: mainFunctions.dbRegisterTenantuser,
  dbRegisterStoreowner: mainFunctions.dbRegisterStoreowner,
  dbGetUser: mainFunctions.dbGetUser,
  dbListUsers: mainFunctions.dbListUsers,
  createUser: mainFunctions.createUser,
  getIdListOfUserByField: mainFunctions.getIdListOfUserByField,
  getUserById: mainFunctions.getUserById,
  getUserAggById: mainFunctions.getUserAggById,
  getUserListByQuery: mainFunctions.getUserListByQuery,
  getUserStatsByQuery: mainFunctions.getUserStatsByQuery,
  getUserByQuery: mainFunctions.getUserByQuery,
  updateUserById: mainFunctions.updateUserById,
  updateUserByIdList: mainFunctions.updateUserByIdList,
  updateUserByQuery: mainFunctions.updateUserByQuery,
  deleteUserById: mainFunctions.deleteUserById,
  deleteUserByQuery: mainFunctions.deleteUserByQuery,
  getUserByEmail: mainFunctions.getUserByEmail,
  getUserByStoreId: mainFunctions.getUserByStoreId,
  dbScriptGetUser: mainFunctions.dbScriptGetUser,
  dbScriptUpdateUser: mainFunctions.dbScriptUpdateUser,
  dbScriptCreateUser: mainFunctions.dbScriptCreateUser,
  dbScriptDeleteUser: mainFunctions.dbScriptDeleteUser,
  dbScriptListUsers: mainFunctions.dbScriptListUsers,
  dbScriptRegisterStoreowner: mainFunctions.dbScriptRegisterStoreowner,
  // UserGroup Db Object
  dbCreateGroup: mainFunctions.dbCreateGroup,
  dbUpdateGroup: mainFunctions.dbUpdateGroup,
  dbGetGroup: mainFunctions.dbGetGroup,
  dbListGroups: mainFunctions.dbListGroups,
  createUserGroup: mainFunctions.createUserGroup,
  getIdListOfUserGroupByField: mainFunctions.getIdListOfUserGroupByField,
  getUserGroupById: mainFunctions.getUserGroupById,
  getUserGroupAggById: mainFunctions.getUserGroupAggById,
  getUserGroupListByQuery: mainFunctions.getUserGroupListByQuery,
  getUserGroupStatsByQuery: mainFunctions.getUserGroupStatsByQuery,
  getUserGroupByQuery: mainFunctions.getUserGroupByQuery,
  updateUserGroupById: mainFunctions.updateUserGroupById,
  updateUserGroupByIdList: mainFunctions.updateUserGroupByIdList,
  updateUserGroupByQuery: mainFunctions.updateUserGroupByQuery,
  deleteUserGroupById: mainFunctions.deleteUserGroupById,
  deleteUserGroupByQuery: mainFunctions.deleteUserGroupByQuery,

  // UserGroupMember Db Object
  dbCreateGroupmember: mainFunctions.dbCreateGroupmember,
  dbDeleteGroupmember: mainFunctions.dbDeleteGroupmember,
  dbGetGroupmember: mainFunctions.dbGetGroupmember,
  dbListGroupmembers: mainFunctions.dbListGroupmembers,
  createUserGroupMember: mainFunctions.createUserGroupMember,
  getIdListOfUserGroupMemberByField:
    mainFunctions.getIdListOfUserGroupMemberByField,
  getUserGroupMemberById: mainFunctions.getUserGroupMemberById,
  getUserGroupMemberAggById: mainFunctions.getUserGroupMemberAggById,
  getUserGroupMemberListByQuery: mainFunctions.getUserGroupMemberListByQuery,
  getUserGroupMemberStatsByQuery: mainFunctions.getUserGroupMemberStatsByQuery,
  getUserGroupMemberByQuery: mainFunctions.getUserGroupMemberByQuery,
  updateUserGroupMemberById: mainFunctions.updateUserGroupMemberById,
  updateUserGroupMemberByIdList: mainFunctions.updateUserGroupMemberByIdList,
  updateUserGroupMemberByQuery: mainFunctions.updateUserGroupMemberByQuery,
  deleteUserGroupMemberById: mainFunctions.deleteUserGroupMemberById,
  deleteUserGroupMemberByQuery: mainFunctions.deleteUserGroupMemberByQuery,

  // Store Db Object
  dbCreateStore: mainFunctions.dbCreateStore,
  dbGetStore: mainFunctions.dbGetStore,
  dbGetStorebycodename: mainFunctions.dbGetStorebycodename,
  dbListRegisteredstores: mainFunctions.dbListRegisteredstores,
  createStore: mainFunctions.createStore,
  getIdListOfStoreByField: mainFunctions.getIdListOfStoreByField,
  getStoreById: mainFunctions.getStoreById,
  getStoreAggById: mainFunctions.getStoreAggById,
  getStoreListByQuery: mainFunctions.getStoreListByQuery,
  getStoreStatsByQuery: mainFunctions.getStoreStatsByQuery,
  getStoreByQuery: mainFunctions.getStoreByQuery,
  updateStoreById: mainFunctions.updateStoreById,
  updateStoreByIdList: mainFunctions.updateStoreByIdList,
  updateStoreByQuery: mainFunctions.updateStoreByQuery,
  deleteStoreById: mainFunctions.deleteStoreById,
  deleteStoreByQuery: mainFunctions.deleteStoreByQuery,
  getNextCodenameForStore: mainFunctions.getNextCodenameForStore,
  getStoreByOwnerId: mainFunctions.getStoreByOwnerId,
};
