const utils = require("./utils");
const dbApiScripts = require("./dbApiScripts");

module.exports = {
  dbCreateUser: require("./dbCreateUser"),
  dbUpdateUser: require("./dbUpdateUser"),
  dbDeleteUser: require("./dbDeleteUser"),
  dbUpdateUserrole: require("./dbUpdateUserrole"),
  dbUpdatePassword: require("./dbUpdatePassword"),
  dbRegisterTenantuser: require("./dbRegisterTenantuser"),
  dbRegisterStoreowner: require("./dbRegisterStoreowner"),
  dbGetUser: require("./dbGetUser"),
  dbListUsers: require("./dbListUsers"),
  createUser: utils.createUser,
  getIdListOfUserByField: utils.getIdListOfUserByField,
  getUserById: utils.getUserById,
  getUserAggById: utils.getUserAggById,
  getUserListByQuery: utils.getUserListByQuery,
  getUserStatsByQuery: utils.getUserStatsByQuery,
  getUserByQuery: utils.getUserByQuery,
  updateUserById: utils.updateUserById,
  updateUserByIdList: utils.updateUserByIdList,
  updateUserByQuery: utils.updateUserByQuery,
  deleteUserById: utils.deleteUserById,
  deleteUserByQuery: utils.deleteUserByQuery,
  getUserByEmail: utils.getUserByEmail,
  getUserByStoreId: utils.getUserByStoreId,
  dbScriptGetUser: dbApiScripts.dbScriptGetUser,
  dbScriptUpdateUser: dbApiScripts.dbScriptUpdateUser,
  dbScriptCreateUser: dbApiScripts.dbScriptCreateUser,
  dbScriptDeleteUser: dbApiScripts.dbScriptDeleteUser,
  dbScriptListUsers: dbApiScripts.dbScriptListUsers,
  dbScriptRegisterStoreowner: dbApiScripts.dbScriptRegisterStoreowner,
};
