module.exports = {
  UserCreatedTopic: "salesai1-auth-service-user-created",
  UserUpdatedTopic: "salesai1-auth-service-user-updated",
  UserDeletedTopic: "salesai1-auth-service-user-deleted",
  UserroleUpdatedTopic: "salesai1-auth-service-userrole-updated",
  PasswordUpdatedTopic: "salesai1-auth-service-password-updated",
  TenantuserRegisterredTopic: "salesai1-auth-service-tenantuser-registerred",
  StoreownerRegisterredTopic: "salesai1-auth-service-storeowner-registerred",
  UserRetrivedTopic: "salesai1-auth-service-user-retrived",
  UsersListedTopic: "salesai1-auth-service-users-listed",
  GroupCreatedTopic: "salesai1-auth-service-group-created",
  GroupUpdatedTopic: "salesai1-auth-service-group-updated",
  GroupRetrivedTopic: "salesai1-auth-service-group-retrived",
  GroupsListedTopic: "salesai1-auth-service-groups-listed",
  GroupmemberCreatedTopic: "salesai1-auth-service-groupmember-created",
  GroupmemberDeletedTopic: "salesai1-auth-service-groupmember-deleted",
  GroupmemberRetrivedTopic: "salesai1-auth-service-groupmember-retrived",
  GroupmembersListedTopic: "salesai1-auth-service-groupmembers-listed",
  StoreCreatedTopic: "salesai1-auth-service-store-created",
  StoreRetrivedTopic: "salesai1-auth-service-store-retrived",
  StorebycodenameRetrivedTopic:
    "salesai1-auth-service-storebycodename-retrived",
  RegisteredstoresListedTopic: "salesai1-auth-service-registeredstores-listed",
};
